### ISSUE TITLE
Table and notion api limit

### ISSUE THREAD

**Issue by apic92** [seratch/notion-translator#8]
Hi, awesome tool, thanks!

I translated a notion page from EN to JA and the tool didn't translate text in table. In Japanese I get the following result on the created page: (このページでは画像を削除しています) // (This page removes the table)

Also only a fraction of the page has been translated: (申し訳ありません。Notion-translatorはNotion公開APIの制限により、以下のブロックを全て省略させていただきました。) // (Sorry, Notion-translator omits all of the following blocks due to limitations of the Notion public API.)

Can it be fixed?

**Comment by seratch** [comment]
@apic92 As far as I know, their public APIs still have the limitations. So, this tool is unable to improve it.
